variable "prefix" {
  description = "Resource prefix name for resources generated by this module. Default: example"
  type        = string
  default     = "example"
}

variable "log_destination_type" {
  description = "The type of the logging destination. Valid values: cloud-watch-logs, s3, kinesis-data-firehose. Default: cloud-watch-logs."
  type        = string
  default     = "cloud-watch-logs"
}

variable "log_destination_arn" {
  description = "Specify the flow log output destination ARN"
  type        = string
  default     = null
}

variable "traffic_type" {
  description = "The type of traffic to capture. Valid values: ACCEPT, REJECT, ALL. Default: ALL."
  type        = string
  default     = "ALL"
}

variable "vpc_id" {
  type    = string
  default = null
}
